spring :
  datasource:
    url: jdbc:h2:mem:securityTest
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools: #어플리케이션 재시작 될때마다 변경 사항 로그로 보여줌
    restart:
      log-condition-evaluation-delta: false

jwt :
  secret : sbIpHRsm1n9tg7zKyWsqxtcPZDjgjCEXdMbrz6+uDAPrkia1KY8WA37dOcoWEbgT  #key
  expiration : 360000 #1hr
  # refresh
  access-token-validity : 900000 #15분
  refresh-token-validity : 604800000 #일주일

springdoc:
  swagger-ui:
    path: /swagger-ui.html


